apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T17:18:54Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4904"
  uid: 4fcff47e-2f4b-40af-b438-785aaa386255
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.56.85
  clusterIPs:
  - 10.103.56.85
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31687
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
